name: machine_task
description: "A Flutter app with Clean Architecture, Google Auth, CRUD operations, and push notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP Client
  dio: ^5.7.0
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Local Storage
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  
  # Connectivity
  connectivity_plus: ^6.0.5
  
  # Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  
  # Localization
  intl: ^0.20.2
  
  # Utilities
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
